// AUTO-GENERATED by scripts/update-public-rules.mjs
// Source: https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/tax-free-savings-account/contributing/calculate-room.html

export type TfsaLimitByYear = Record<string, number>;

export const TFSA_ANNUAL_LIMIT_BY_YEAR = {
  "2009": 5000,
  "2010": 5000,
  "2011": 5000,
  "2012": 5000,
  "2013": 5500,
  "2014": 5500,
  "2015": 10000,
  "2016": 5500,
  "2017": 5500,
  "2018": 5500,
  "2019": 6000,
  "2020": 6000,
  "2021": 6000,
  "2022": 18000,
  "2023": 6500,
  "2024": 6000,
  "2025": 7000,
  "2026": 7000,
} as const;


export const FHSA_RULES = {
  annualLimitPerPerson: 8000,
  lifetimeCapPerPerson: 40000,
} as const;
